"""
Pytest configuration and synthetic NetCDF test fixtures.

NOTE: All NetCDF datasets generated in this module are TINY SYNTHETIC FIXTURES
used exclusively for automated unit testing of ingestion pipeline logic.
They are NOT real ARGO ocean observations.
"""

import sys
from pathlib import Path
import pytest
import numpy as np
import xarray as xr

# Ensure project root is on sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


@pytest.fixture
def synthetic_argo_dataset():
    """
    Construct an in-memory xarray Dataset simulating a multi-profile ARGO Core NetCDF file.
    Includes 2 profiles:
      - Profile 0: Bay of Bengal (Lat 15.0°N, Lon 88.0°E), valid QC flags ('1')
      - Profile 1: Arabian Sea (Lat 12.0°N, Lon 65.0°E), mixed QC flags ('1', '4')
    """
    n_prof = 2
    n_levels = 5

    # Coordinates / Dimensions
    juld = np.array([26000.0, 26001.0], dtype=np.float64)  # approx year 2021
    lat = np.array([15.0, 12.0], dtype=np.float32)
    lon = np.array([88.0, 65.0], dtype=np.float32)

    platform_number = np.array([b"2901633 ", b"6901452 "], dtype="S8")
    cycle_number = np.array([1, 2], dtype=np.int32)

    position_qc = np.array([b"1", b"1"], dtype="S1")
    juld_qc = np.array([b"1", b"1"], dtype="S1")

    # 2D arrays: (N_PROF, N_LEVELS)
    pres = np.array([
        [10.0, 50.0, 100.0, 200.0, 500.0],
        [10.0, 50.0, 100.0, 200.0, 500.0]
    ], dtype=np.float32)

    temp = np.array([
        [28.5, 26.2, 22.1, 18.0, 10.5],
        [29.0, 25.0, 21.0, 17.5, 9.8]
    ], dtype=np.float32)

    temp_qc = np.array([
        [b"1", b"1", b"1", b"1", b"1"],
        [b"1", b"1", b"4", b"1", b"1"]  # level 2 has bad QC '4'
    ], dtype="S1")

    psal = np.array([
        [34.5, 34.7, 35.0, 35.1, 35.0],
        [35.5, 35.8, 36.0, 35.9, 35.5]
    ], dtype=np.float32)

    psal_qc = np.array([
        [b"1", b"1", b"1", b"1", b"1"],
        [b"1", b"1", b"1", b"1", b"1"]
    ], dtype="S1")

    ds = xr.Dataset(
        data_vars={
            "PLATFORM_NUMBER": (("N_PROF",), platform_number),
            "CYCLE_NUMBER": (("N_PROF",), cycle_number),
            "JULD": (("N_PROF",), juld),
            "JULD_QC": (("N_PROF",), juld_qc),
            "LATITUDE": (("N_PROF",), lat),
            "LONGITUDE": (("N_PROF",), lon),
            "POSITION_QC": (("N_PROF",), position_qc),
            "PRES": (("N_PROF", "N_LEVELS"), pres),
            "TEMP": (("N_PROF", "N_LEVELS"), temp),
            "TEMP_QC": (("N_PROF", "N_LEVELS"), temp_qc),
            "PSAL": (("N_PROF", "N_LEVELS"), psal),
            "PSAL_QC": (("N_PROF", "N_LEVELS"), psal_qc),
        },
        attrs={
            "title": "SYNTHETIC ARGO TEST FIXTURE FOR UNIT TESTING ONLY",
            "source": "Synthetic test fixture generated by pytest conftest"
        }
    )
    return ds


@pytest.fixture
def temp_nc_file(tmp_path, synthetic_argo_dataset):
    """Write synthetic dataset to a temporary NetCDF file on disk."""
    file_path = tmp_path / "test_prof.nc"
    synthetic_argo_dataset.to_netcdf(file_path, engine="netcdf4")
    return file_path
